name: Update Clone Badge

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily

jobs:
  update-badge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch Clone Count
        id: fetch_clones
        run: |
          CLONE_COUNT=$(curl -H "Authorization: token ${{ secrets.TOKEN }}" \
                         -s https://api.github.com/repos/Lychan23/Ly.JSxPy/traffic/clones \
                         | jq '.total')
          
          # Use jq to parse the JSON response
          echo "CLONE_COUNT=$CLONE_COUNT" >> $GITHUB_ENV

      - name: Update Clone Badge
        run: |
          # Use the value of CLONE_COUNT from the previous step
          BADGE_URL="https://img.shields.io/badge/Clones-${{ env.CLONE_COUNT }}-blue"
          
          # Update the README.md with the new badge URL
          echo "![Clone Count]($BADGE_URL)" > README.md
          
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git commit -m "Update clone count badge"
          git push
